name: Release
on:
  push:
    branches:
      - main
env:
  TEST_GITLAB_ACCESS_TOKEN: ${{ secrets.TEST_GITLAB_ACCESS_TOKEN }}
  TEST_PROJECT_ID: ${{ secrets.TEST_PROJECT_ID }}
jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: asdf_install
        uses: asdf-vm/actions/install@v1
      - name: Install dependencies
        run: (cd reminder && npm ci)
      - name: Run tests Image
        run: (cd reminder && npm run test)
  release:
    name: Release
    runs-on: ubuntu-latest
    needs:
    - test
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: asdf_install
        uses: asdf-vm/actions/install@v1
      - name: Install dependencies
        run: npm ci
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      - name: Login to DockerHub
        uses: docker/login-action@v1 
      - name: Release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: npm run release
      - name: Merge main into develop
        uses: devmasx/merge-branch@master
        with:
          type: now
          message: "chore: Merged main into develop"
          from_branch: main
          target_branch: develop
          github_token: ${{ secrets.GITHUB_TOKEN }}
